# Generated by Django 3.1.6 on 2022-10-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(blank='false', max_length=100, null='false', verbose_name='Nome do cliente')),
                ('dataDaEntrada', models.DateTimeField(auto_now_add=True, verbose_name='Entrou:')),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
