# Generated by Django 3.1.6 on 2022-10-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clienteConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divida', models.FloatField()),
                ('inicioDaDivida', models.DateTimeField(auto_now_add=True, verbose_name='Começo da dívida')),
                ('mudancaDaDivida', models.DateTimeField(auto_now=True)),
                ('conta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Conta do cliente:')),
            ],
        ),
    ]
