# Generated by Django 3.1.6 on 2022-10-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clienteconta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteconta',
            name='descricao',
            field=models.CharField(blank='false', max_length=200, null='false', verbose_name='Descrição da dívida:'),
            preserve_default='false',
        ),
        migrations.AlterField(
            model_name='clienteconta',
            name='divida',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
